language: generic

sudo: required

env:
  global:
  - PATH="/opt/chefdk/bin:/opt/chefdk/embedded/bin:/opt/chef/bin:$PATH"

addons:
  apt:
    sources:
    - chef-stable-precise
    packages:
    - chefdk

script:
- foodcritic chef/cookbooks/ckrst
- foodcritic chef/cookbooks/web
- chef exec rspec chef/cookbooks/ckrst
- chef exec rspec chef/cookbooks/web
