source "https://supermarket.chef.io"

cookbook 'git'
cookbook 'zip'
cookbook 'php'
cookbook 'apt'
cookbook 'apache2'
cookbook 'nodejs'
cookbook 'docker'
cookbook 'ruby2', git: "https://github.com/vinik/ruby2_cookbook.git"
